<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1rQ8ZMO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1rQ8ZMO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1rQ8ZMO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1rQ8ZMO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1rQ8ZMO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1rQ8ZMO',
    'container.build_id' => '21d47fc3',
    'container.build_time' => 1621699866,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1rQ8ZMO');
