<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'exportOrdersCSV' => [[], ['_controller' => 'App\\Controller\\OrderController::csv'], [], [['text', '/order/csv']], [], []],
    'viewOrders' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'editOrder' => [['orderID'], ['_controller' => 'App\\Controller\\OrderController::edit'], [], [['variable', '/', '[^/]++', 'orderID'], ['text', '/order/edit']], [], []],
    'fetchOrders' => [[], ['_controller' => 'App\\Controller\\OrderController::fetch'], [], [['text', '/order/fetch']], [], []],
    'orderEdited' => [['orderID'], ['_controller' => 'App\\Controller\\OrderController::edited'], [], [['variable', '/', '[^/]++', 'orderID'], ['text', '/order/edited']], [], []],
    'deleteOrder' => [['orderID'], ['_controller' => 'App\\Controller\\OrderController::delete'], [], [['variable', '/', '[^/]++', 'orderID'], ['text', '/order/delete']], [], []],
    'exportProductsCSV' => [[], ['_controller' => 'App\\Controller\\ProductsController::csv'], [], [['text', '/product/csv']], [], []],
    'viewProducts' => [[], ['_controller' => 'App\\Controller\\ProductsController::index'], [], [['text', '/product']], [], []],
    'editProduct' => [['uid'], ['_controller' => 'App\\Controller\\ProductsController::edit'], [], [['variable', '/', '[^/]++', 'uid'], ['text', '/product/edit']], [], []],
    'fetchProducts' => [[], ['_controller' => 'App\\Controller\\ProductsController::fetch'], [], [['text', '/product/fetch']], [], []],
    'productEdited' => [['uid'], ['_controller' => 'App\\Controller\\ProductsController::edited'], [], [['variable', '/', '[^/]++', 'uid'], ['text', '/product/edited']], [], []],
    'deleteProduct' => [['uid'], ['_controller' => 'App\\Controller\\ProductsController::delete'], [], [['variable', '/', '[^/]++', 'uid'], ['text', '/product/delete']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
